// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/ml/ml_service.proto

package ml

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLPredictionService_Predict_FullMethodName         = "/ml.MLPredictionService/Predict"
	MLPredictionService_TrainModel_FullMethodName      = "/ml.MLPredictionService/TrainModel"
	MLPredictionService_GetModelInfo_FullMethodName    = "/ml.MLPredictionService/GetModelInfo"
	MLPredictionService_Ping_FullMethodName            = "/ml.MLPredictionService/Ping"
	MLPredictionService_TriggerTraining_FullMethodName = "/ml.MLPredictionService/TriggerTraining"
)

// MLPredictionServiceClient is the client API for MLPredictionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ML Prediction Service
// Provides stock price prediction using XGBoost quantile regression models
type MLPredictionServiceClient interface {
	// Generate prediction for a stock on a specific date
	// Returns three quantile predictions (p10, p50, p90)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Train or retrain models for a specific stock
	// Returns training results and validation metrics
	TrainModel(ctx context.Context, in *TrainModelRequest, opts ...grpc.CallOption) (*TrainModelResponse, error)
	// Get information about currently deployed models
	// Returns model metadata including version, metrics, and training dates
	GetModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error)
	// Simple health check
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Trigger training automation (backfill + train)
	// Simplified interface for Telegram bot automation
	TriggerTraining(ctx context.Context, in *TriggerTrainingRequest, opts ...grpc.CallOption) (*TriggerTrainingResponse, error)
}

type mLPredictionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLPredictionServiceClient(cc grpc.ClientConnInterface) MLPredictionServiceClient {
	return &mLPredictionServiceClient{cc}
}

func (c *mLPredictionServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, MLPredictionService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLPredictionServiceClient) TrainModel(ctx context.Context, in *TrainModelRequest, opts ...grpc.CallOption) (*TrainModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainModelResponse)
	err := c.cc.Invoke(ctx, MLPredictionService_TrainModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLPredictionServiceClient) GetModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfoResponse)
	err := c.cc.Invoke(ctx, MLPredictionService_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLPredictionServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MLPredictionService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLPredictionServiceClient) TriggerTraining(ctx context.Context, in *TriggerTrainingRequest, opts ...grpc.CallOption) (*TriggerTrainingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerTrainingResponse)
	err := c.cc.Invoke(ctx, MLPredictionService_TriggerTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLPredictionServiceServer is the server API for MLPredictionService service.
// All implementations must embed UnimplementedMLPredictionServiceServer
// for forward compatibility.
//
// ML Prediction Service
// Provides stock price prediction using XGBoost quantile regression models
type MLPredictionServiceServer interface {
	// Generate prediction for a stock on a specific date
	// Returns three quantile predictions (p10, p50, p90)
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// Train or retrain models for a specific stock
	// Returns training results and validation metrics
	TrainModel(context.Context, *TrainModelRequest) (*TrainModelResponse, error)
	// Get information about currently deployed models
	// Returns model metadata including version, metrics, and training dates
	GetModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error)
	// Simple health check
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Trigger training automation (backfill + train)
	// Simplified interface for Telegram bot automation
	TriggerTraining(context.Context, *TriggerTrainingRequest) (*TriggerTrainingResponse, error)
	mustEmbedUnimplementedMLPredictionServiceServer()
}

// UnimplementedMLPredictionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLPredictionServiceServer struct{}

func (UnimplementedMLPredictionServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMLPredictionServiceServer) TrainModel(context.Context, *TrainModelRequest) (*TrainModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainModel not implemented")
}
func (UnimplementedMLPredictionServiceServer) GetModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedMLPredictionServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMLPredictionServiceServer) TriggerTraining(context.Context, *TriggerTrainingRequest) (*TriggerTrainingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerTraining not implemented")
}
func (UnimplementedMLPredictionServiceServer) mustEmbedUnimplementedMLPredictionServiceServer() {}
func (UnimplementedMLPredictionServiceServer) testEmbeddedByValue()                             {}

// UnsafeMLPredictionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLPredictionServiceServer will
// result in compilation errors.
type UnsafeMLPredictionServiceServer interface {
	mustEmbedUnimplementedMLPredictionServiceServer()
}

func RegisterMLPredictionServiceServer(s grpc.ServiceRegistrar, srv MLPredictionServiceServer) {
	// If the following call panics, it indicates UnimplementedMLPredictionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLPredictionService_ServiceDesc, srv)
}

func _MLPredictionService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLPredictionServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLPredictionService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLPredictionServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLPredictionService_TrainModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLPredictionServiceServer).TrainModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLPredictionService_TrainModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLPredictionServiceServer).TrainModel(ctx, req.(*TrainModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLPredictionService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLPredictionServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLPredictionService_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLPredictionServiceServer).GetModelInfo(ctx, req.(*ModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLPredictionService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLPredictionServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLPredictionService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLPredictionServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLPredictionService_TriggerTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLPredictionServiceServer).TriggerTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLPredictionService_TriggerTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLPredictionServiceServer).TriggerTraining(ctx, req.(*TriggerTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLPredictionService_ServiceDesc is the grpc.ServiceDesc for MLPredictionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLPredictionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.MLPredictionService",
	HandlerType: (*MLPredictionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _MLPredictionService_Predict_Handler,
		},
		{
			MethodName: "TrainModel",
			Handler:    _MLPredictionService_TrainModel_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _MLPredictionService_GetModelInfo_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MLPredictionService_Ping_Handler,
		},
		{
			MethodName: "TriggerTraining",
			Handler:    _MLPredictionService_TriggerTraining_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ml/ml_service.proto",
}
