// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/ml/ml_service.proto

package ml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Optional message (e.g. "ping")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "pong"
	ServerTime    string                 `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Request message for prediction
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`                                                                                 // Stock ticker symbol (e.g., "HPG")
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                                                                                     // Date for prediction in YYYY-MM-DD format
	Features      map[string]float64     `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Optional: pre-calculated features (if empty, service calculates them)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *PredictRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *PredictRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PredictRequest) GetFeatures() map[string]float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

// Response message for prediction
type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P10           float64                `protobuf:"fixed64,1,opt,name=p10,proto3" json:"p10,omitempty"`                                     // 10th percentile prediction (downside risk) - Horizon 1
	P50           float64                `protobuf:"fixed64,2,opt,name=p50,proto3" json:"p50,omitempty"`                                     // 50th percentile prediction (expected return) - Horizon 1
	P90           float64                `protobuf:"fixed64,3,opt,name=p90,proto3" json:"p90,omitempty"`                                     // 90th percentile prediction (upside potential) - Horizon 1
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // Confidence score (0-1) - Horizon 1
	ModelVersion  string                 `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // Version identifier of models used
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`                              // Whether prediction succeeded
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if success=false
	Predictions   []*HorizonPrediction   `protobuf:"bytes,8,rep,name=predictions,proto3" json:"predictions,omitempty"`                       // Multi-horizon predictions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *PredictResponse) GetP10() float64 {
	if x != nil {
		return x.P10
	}
	return 0
}

func (x *PredictResponse) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *PredictResponse) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

func (x *PredictResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *PredictResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PredictResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PredictResponse) GetPredictions() []*HorizonPrediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type HorizonPrediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Horizon       int32                  `protobuf:"varint,1,opt,name=horizon,proto3" json:"horizon,omitempty"`        // Forecast horizon (days)
	P10           float64                `protobuf:"fixed64,2,opt,name=p10,proto3" json:"p10,omitempty"`               // 10th percentile
	P50           float64                `protobuf:"fixed64,3,opt,name=p50,proto3" json:"p50,omitempty"`               // 50th percentile
	P90           float64                `protobuf:"fixed64,4,opt,name=p90,proto3" json:"p90,omitempty"`               // 90th percentile
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // Confidence score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HorizonPrediction) Reset() {
	*x = HorizonPrediction{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HorizonPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorizonPrediction) ProtoMessage() {}

func (x *HorizonPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorizonPrediction.ProtoReflect.Descriptor instead.
func (*HorizonPrediction) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{4}
}

func (x *HorizonPrediction) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

func (x *HorizonPrediction) GetP10() float64 {
	if x != nil {
		return x.P10
	}
	return 0
}

func (x *HorizonPrediction) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *HorizonPrediction) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

func (x *HorizonPrediction) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Request message for model training
type TrainModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`                                  // Stock ticker to train models for
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`                                     // Number of historical days to use for training (default: 252)
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                                   // Force retrain even if recent models exist
	ValidateOnly  bool                   `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"` // Only validate existing models, don't retrain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainModelRequest) Reset() {
	*x = TrainModelRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainModelRequest) ProtoMessage() {}

func (x *TrainModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainModelRequest.ProtoReflect.Descriptor instead.
func (*TrainModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *TrainModelRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *TrainModelRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *TrainModelRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TrainModelRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

// Response message for model training
type TrainModelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                      // Whether training succeeded
	ModelVersion   string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`         // Version identifier of newly trained models
	MaeValidation  float64                `protobuf:"fixed64,3,opt,name=mae_validation,json=maeValidation,proto3" json:"mae_validation,omitempty"`    // Mean Absolute Error on validation set
	IcValidation   float64                `protobuf:"fixed64,4,opt,name=ic_validation,json=icValidation,proto3" json:"ic_validation,omitempty"`       // Information Coefficient on validation set
	TrainDays      int32                  `protobuf:"varint,5,opt,name=train_days,json=trainDays,proto3" json:"train_days,omitempty"`                 // Actual number of days used for training
	TrainStartDate string                 `protobuf:"bytes,6,opt,name=train_start_date,json=trainStartDate,proto3" json:"train_start_date,omitempty"` // Start date of training period
	TrainEndDate   string                 `protobuf:"bytes,7,opt,name=train_end_date,json=trainEndDate,proto3" json:"train_end_date,omitempty"`       // End date of training period
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`         // Error message if success=false
	Metrics        *ModelMetrics          `protobuf:"bytes,9,opt,name=metrics,proto3" json:"metrics,omitempty"`                                       // Detailed training metrics
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainModelResponse) Reset() {
	*x = TrainModelResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainModelResponse) ProtoMessage() {}

func (x *TrainModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainModelResponse.ProtoReflect.Descriptor instead.
func (*TrainModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{6}
}

func (x *TrainModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainModelResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *TrainModelResponse) GetMaeValidation() float64 {
	if x != nil {
		return x.MaeValidation
	}
	return 0
}

func (x *TrainModelResponse) GetIcValidation() float64 {
	if x != nil {
		return x.IcValidation
	}
	return 0
}

func (x *TrainModelResponse) GetTrainDays() int32 {
	if x != nil {
		return x.TrainDays
	}
	return 0
}

func (x *TrainModelResponse) GetTrainStartDate() string {
	if x != nil {
		return x.TrainStartDate
	}
	return ""
}

func (x *TrainModelResponse) GetTrainEndDate() string {
	if x != nil {
		return x.TrainEndDate
	}
	return ""
}

func (x *TrainModelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TrainModelResponse) GetMetrics() *ModelMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Request message for model info
type ModelInfoRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ticker             string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`                                                      // Stock ticker to get model info for
	IncludeAllVersions bool                   `protobuf:"varint,2,opt,name=include_all_versions,json=includeAllVersions,proto3" json:"include_all_versions,omitempty"` // Include all versions or only production models
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{7}
}

func (x *ModelInfoRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *ModelInfoRequest) GetIncludeAllVersions() bool {
	if x != nil {
		return x.IncludeAllVersions
	}
	return false
}

// Response message for model info
type ModelInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`                                 // List of model information
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // Whether request succeeded
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoResponse) Reset() {
	*x = ModelInfoResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoResponse) ProtoMessage() {}

func (x *ModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{8}
}

func (x *ModelInfoResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ModelInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ModelInfoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Model information
type ModelInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelId         string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                                                                               // Unique model identifier
	Ticker          string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`                                                                                                // Stock ticker
	Quantile        float64                `protobuf:"fixed64,3,opt,name=quantile,proto3" json:"quantile,omitempty"`                                                                                          // Quantile level (0.10, 0.50, or 0.90)
	TrainingDate    string                 `protobuf:"bytes,4,opt,name=training_date,json=trainingDate,proto3" json:"training_date,omitempty"`                                                                // Date when model was trained
	TrainStartDate  string                 `protobuf:"bytes,5,opt,name=train_start_date,json=trainStartDate,proto3" json:"train_start_date,omitempty"`                                                        // Start of training period
	TrainEndDate    string                 `protobuf:"bytes,6,opt,name=train_end_date,json=trainEndDate,proto3" json:"train_end_date,omitempty"`                                                              // End of training period
	TrainDays       int32                  `protobuf:"varint,7,opt,name=train_days,json=trainDays,proto3" json:"train_days,omitempty"`                                                                        // Number of training days
	InProduction    bool                   `protobuf:"varint,8,opt,name=in_production,json=inProduction,proto3" json:"in_production,omitempty"`                                                               // Whether this model is currently in production
	FilePath        string                 `protobuf:"bytes,9,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                                                            // Path to saved model file
	Hyperparameters map[string]float64     `protobuf:"bytes,10,rep,name=hyperparameters,proto3" json:"hyperparameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Model hyperparameters
	Metrics         *ModelMetrics          `protobuf:"bytes,11,opt,name=metrics,proto3" json:"metrics,omitempty"`                                                                                             // Validation metrics
	Horizon         int32                  `protobuf:"varint,12,opt,name=horizon,proto3" json:"horizon,omitempty"`                                                                                            // Prediction horizon (1, 5, 10 etc.)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{9}
}

func (x *ModelInfo) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelInfo) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *ModelInfo) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

func (x *ModelInfo) GetTrainingDate() string {
	if x != nil {
		return x.TrainingDate
	}
	return ""
}

func (x *ModelInfo) GetTrainStartDate() string {
	if x != nil {
		return x.TrainStartDate
	}
	return ""
}

func (x *ModelInfo) GetTrainEndDate() string {
	if x != nil {
		return x.TrainEndDate
	}
	return ""
}

func (x *ModelInfo) GetTrainDays() int32 {
	if x != nil {
		return x.TrainDays
	}
	return 0
}

func (x *ModelInfo) GetInProduction() bool {
	if x != nil {
		return x.InProduction
	}
	return false
}

func (x *ModelInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ModelInfo) GetHyperparameters() map[string]float64 {
	if x != nil {
		return x.Hyperparameters
	}
	return nil
}

func (x *ModelInfo) GetMetrics() *ModelMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ModelInfo) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

// Detailed model metrics
type ModelMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Mae                 float64                `protobuf:"fixed64,1,opt,name=mae,proto3" json:"mae,omitempty"`                                                            // Mean Absolute Error
	Rmse                float64                `protobuf:"fixed64,2,opt,name=rmse,proto3" json:"rmse,omitempty"`                                                          // Root Mean Square Error
	Ic                  float64                `protobuf:"fixed64,3,opt,name=ic,proto3" json:"ic,omitempty"`                                                              // Information Coefficient (prediction-outcome correlation)
	DirectionalAccuracy float64                `protobuf:"fixed64,4,opt,name=directional_accuracy,json=directionalAccuracy,proto3" json:"directional_accuracy,omitempty"` // Percentage of correct direction predictions
	P10Calibration      float64                `protobuf:"fixed64,5,opt,name=p10_calibration,json=p10Calibration,proto3" json:"p10_calibration,omitempty"`                // Actual percentage of outcomes below p10 (should be ~10%)
	P90Calibration      float64                `protobuf:"fixed64,6,opt,name=p90_calibration,json=p90Calibration,proto3" json:"p90_calibration,omitempty"`                // Actual percentage of outcomes above p90 (should be ~10%)
	ValSamples          int32                  `protobuf:"varint,7,opt,name=val_samples,json=valSamples,proto3" json:"val_samples,omitempty"`                             // Number of validation samples
	Horizon             int32                  `protobuf:"varint,8,opt,name=horizon,proto3" json:"horizon,omitempty"`                                                     // Horizon for these metrics
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelMetrics) Reset() {
	*x = ModelMetrics{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetrics) ProtoMessage() {}

func (x *ModelMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetrics.ProtoReflect.Descriptor instead.
func (*ModelMetrics) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{10}
}

func (x *ModelMetrics) GetMae() float64 {
	if x != nil {
		return x.Mae
	}
	return 0
}

func (x *ModelMetrics) GetRmse() float64 {
	if x != nil {
		return x.Rmse
	}
	return 0
}

func (x *ModelMetrics) GetIc() float64 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *ModelMetrics) GetDirectionalAccuracy() float64 {
	if x != nil {
		return x.DirectionalAccuracy
	}
	return 0
}

func (x *ModelMetrics) GetP10Calibration() float64 {
	if x != nil {
		return x.P10Calibration
	}
	return 0
}

func (x *ModelMetrics) GetP90Calibration() float64 {
	if x != nil {
		return x.P90Calibration
	}
	return 0
}

func (x *ModelMetrics) GetValSamples() int32 {
	if x != nil {
		return x.ValSamples
	}
	return 0
}

func (x *ModelMetrics) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

// Request for automated training trigger
type TriggerTrainingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"` // Stock ticker to train
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTrainingRequest) Reset() {
	*x = TriggerTrainingRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTrainingRequest) ProtoMessage() {}

func (x *TriggerTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTrainingRequest.ProtoReflect.Descriptor instead.
func (*TriggerTrainingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerTrainingRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

// Response for automated training trigger
type TriggerTrainingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Whether training completed successfully
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // Version of newly trained model
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if success=false
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                 // Status: \"complete\", \"error\"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTrainingResponse) Reset() {
	*x = TriggerTrainingResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTrainingResponse) ProtoMessage() {}

func (x *TriggerTrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTrainingResponse.ProtoReflect.Descriptor instead.
func (*TriggerTrainingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerTrainingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerTrainingResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *TriggerTrainingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TriggerTrainingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request for weekly portfolio selection run
type RunWeeklyPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PredDate      string                 `protobuf:"bytes,1,opt,name=pred_date,json=predDate,proto3" json:"pred_date,omitempty"` // Optional: YYYY-MM-DD. Empty = use latest from DB.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWeeklyPortfolioRequest) Reset() {
	*x = RunWeeklyPortfolioRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWeeklyPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWeeklyPortfolioRequest) ProtoMessage() {}

func (x *RunWeeklyPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWeeklyPortfolioRequest.ProtoReflect.Descriptor instead.
func (*RunWeeklyPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{13}
}

func (x *RunWeeklyPortfolioRequest) GetPredDate() string {
	if x != nil {
		return x.PredDate
	}
	return ""
}

// Response for weekly portfolio selection run
type RunWeeklyPortfolioResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                    // Whether the run completed successfully
	PredDate       string                 `protobuf:"bytes,2,opt,name=pred_date,json=predDate,proto3" json:"pred_date,omitempty"`                   // Actual prediction date used
	MessagesSent   int32                  `protobuf:"varint,3,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`      // Number of report messages generated
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // Error message if success=false
	ReportMessages []string               `protobuf:"bytes,5,rep,name=report_messages,json=reportMessages,proto3" json:"report_messages,omitempty"` // The formatted report strings — Go sends these to Telegram
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunWeeklyPortfolioResponse) Reset() {
	*x = RunWeeklyPortfolioResponse{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWeeklyPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWeeklyPortfolioResponse) ProtoMessage() {}

func (x *RunWeeklyPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWeeklyPortfolioResponse.ProtoReflect.Descriptor instead.
func (*RunWeeklyPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{14}
}

func (x *RunWeeklyPortfolioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunWeeklyPortfolioResponse) GetPredDate() string {
	if x != nil {
		return x.PredDate
	}
	return ""
}

func (x *RunWeeklyPortfolioResponse) GetMessagesSent() int32 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *RunWeeklyPortfolioResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunWeeklyPortfolioResponse) GetReportMessages() []string {
	if x != nil {
		return x.ReportMessages
	}
	return nil
}

// Request for bulk retrain of all tickers
type TriggerBulkRetrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // Force retrain even if models are up to date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBulkRetrainRequest) Reset() {
	*x = TriggerBulkRetrainRequest{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBulkRetrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBulkRetrainRequest) ProtoMessage() {}

func (x *TriggerBulkRetrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBulkRetrainRequest.ProtoReflect.Descriptor instead.
func (*TriggerBulkRetrainRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerBulkRetrainRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// One progress update streamed back to Go for each ticker (and final summary)
type BulkRetrainUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`                   // Ticker being processed (empty on final summary)
	Idx           int32                  `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`                        // Current ticker index (1-based)
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                    // Total tickers in the job
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                // Whether this ticker succeeded
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                 // Human-readable status line for Telegram
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // True on the last summary update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRetrainUpdate) Reset() {
	*x = BulkRetrainUpdate{}
	mi := &file_proto_ml_ml_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRetrainUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRetrainUpdate) ProtoMessage() {}

func (x *BulkRetrainUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_ml_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRetrainUpdate.ProtoReflect.Descriptor instead.
func (*BulkRetrainUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ml_ml_service_proto_rawDescGZIP(), []int{16}
}

func (x *BulkRetrainUpdate) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *BulkRetrainUpdate) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *BulkRetrainUpdate) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BulkRetrainUpdate) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkRetrainUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BulkRetrainUpdate) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_proto_ml_ml_service_proto protoreflect.FileDescriptor

const file_proto_ml_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ml/ml_service.proto\x12\x02ml\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"c\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xb7\x01\n" +
	"\x0ePredictRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12<\n" +
	"\bfeatures\x18\x03 \x03(\v2 .ml.PredictRequest.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x84\x02\n" +
	"\x0fPredictResponse\x12\x10\n" +
	"\x03p10\x18\x01 \x01(\x01R\x03p10\x12\x10\n" +
	"\x03p50\x18\x02 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\x03 \x01(\x01R\x03p90\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x127\n" +
	"\vpredictions\x18\b \x03(\v2\x15.ml.HorizonPredictionR\vpredictions\"\x83\x01\n" +
	"\x11HorizonPrediction\x12\x18\n" +
	"\ahorizon\x18\x01 \x01(\x05R\ahorizon\x12\x10\n" +
	"\x03p10\x18\x02 \x01(\x01R\x03p10\x12\x10\n" +
	"\x03p50\x18\x03 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\x04 \x01(\x01R\x03p90\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\"z\n" +
	"\x11TrainModelRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\"\xdf\x02\n" +
	"\x12TrainModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12%\n" +
	"\x0emae_validation\x18\x03 \x01(\x01R\rmaeValidation\x12#\n" +
	"\ric_validation\x18\x04 \x01(\x01R\ficValidation\x12\x1d\n" +
	"\n" +
	"train_days\x18\x05 \x01(\x05R\ttrainDays\x12(\n" +
	"\x10train_start_date\x18\x06 \x01(\tR\x0etrainStartDate\x12$\n" +
	"\x0etrain_end_date\x18\a \x01(\tR\ftrainEndDate\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12*\n" +
	"\ametrics\x18\t \x01(\v2\x10.ml.ModelMetricsR\ametrics\"\\\n" +
	"\x10ModelInfoRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x120\n" +
	"\x14include_all_versions\x18\x02 \x01(\bR\x12includeAllVersions\"y\n" +
	"\x11ModelInfoResponse\x12%\n" +
	"\x06models\x18\x01 \x03(\v2\r.ml.ModelInfoR\x06models\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x88\x04\n" +
	"\tModelInfo\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bquantile\x18\x03 \x01(\x01R\bquantile\x12#\n" +
	"\rtraining_date\x18\x04 \x01(\tR\ftrainingDate\x12(\n" +
	"\x10train_start_date\x18\x05 \x01(\tR\x0etrainStartDate\x12$\n" +
	"\x0etrain_end_date\x18\x06 \x01(\tR\ftrainEndDate\x12\x1d\n" +
	"\n" +
	"train_days\x18\a \x01(\x05R\ttrainDays\x12#\n" +
	"\rin_production\x18\b \x01(\bR\finProduction\x12\x1b\n" +
	"\tfile_path\x18\t \x01(\tR\bfilePath\x12L\n" +
	"\x0fhyperparameters\x18\n" +
	" \x03(\v2\".ml.ModelInfo.HyperparametersEntryR\x0fhyperparameters\x12*\n" +
	"\ametrics\x18\v \x01(\v2\x10.ml.ModelMetricsR\ametrics\x12\x18\n" +
	"\ahorizon\x18\f \x01(\x05R\ahorizon\x1aB\n" +
	"\x14HyperparametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x84\x02\n" +
	"\fModelMetrics\x12\x10\n" +
	"\x03mae\x18\x01 \x01(\x01R\x03mae\x12\x12\n" +
	"\x04rmse\x18\x02 \x01(\x01R\x04rmse\x12\x0e\n" +
	"\x02ic\x18\x03 \x01(\x01R\x02ic\x121\n" +
	"\x14directional_accuracy\x18\x04 \x01(\x01R\x13directionalAccuracy\x12'\n" +
	"\x0fp10_calibration\x18\x05 \x01(\x01R\x0ep10Calibration\x12'\n" +
	"\x0fp90_calibration\x18\x06 \x01(\x01R\x0ep90Calibration\x12\x1f\n" +
	"\vval_samples\x18\a \x01(\x05R\n" +
	"valSamples\x12\x18\n" +
	"\ahorizon\x18\b \x01(\x05R\ahorizon\"0\n" +
	"\x16TriggerTrainingRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"\x95\x01\n" +
	"\x17TriggerTrainingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"8\n" +
	"\x19RunWeeklyPortfolioRequest\x12\x1b\n" +
	"\tpred_date\x18\x01 \x01(\tR\bpredDate\"\xc6\x01\n" +
	"\x1aRunWeeklyPortfolioResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tpred_date\x18\x02 \x01(\tR\bpredDate\x12#\n" +
	"\rmessages_sent\x18\x03 \x01(\x05R\fmessagesSent\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0freport_messages\x18\x05 \x03(\tR\x0ereportMessages\"1\n" +
	"\x19TriggerBulkRetrainRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\xa2\x01\n" +
	"\x11BulkRetrainUpdate\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal2\xdd\x03\n" +
	"\x13MLPredictionService\x122\n" +
	"\aPredict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponse\x12;\n" +
	"\n" +
	"TrainModel\x12\x15.ml.TrainModelRequest\x1a\x16.ml.TrainModelResponse\x12;\n" +
	"\fGetModelInfo\x12\x14.ml.ModelInfoRequest\x1a\x15.ml.ModelInfoResponse\x12)\n" +
	"\x04Ping\x12\x0f.ml.PingRequest\x1a\x10.ml.PingResponse\x12J\n" +
	"\x0fTriggerTraining\x12\x1a.ml.TriggerTrainingRequest\x1a\x1b.ml.TriggerTrainingResponse\x12S\n" +
	"\x12RunWeeklyPortfolio\x12\x1d.ml.RunWeeklyPortfolioRequest\x1a\x1e.ml.RunWeeklyPortfolioResponse\x12L\n" +
	"\x12TriggerBulkRetrain\x12\x1d.ml.TriggerBulkRetrainRequest\x1a\x15.ml.BulkRetrainUpdate0\x01B3Z1github.com/nonobeam/golang-stock-trading/proto/mlb\x06proto3"

var (
	file_proto_ml_ml_service_proto_rawDescOnce sync.Once
	file_proto_ml_ml_service_proto_rawDescData []byte
)

func file_proto_ml_ml_service_proto_rawDescGZIP() []byte {
	file_proto_ml_ml_service_proto_rawDescOnce.Do(func() {
		file_proto_ml_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ml_ml_service_proto_rawDesc), len(file_proto_ml_ml_service_proto_rawDesc)))
	})
	return file_proto_ml_ml_service_proto_rawDescData
}

var file_proto_ml_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ml_ml_service_proto_goTypes = []any{
	(*PingRequest)(nil),                // 0: ml.PingRequest
	(*PingResponse)(nil),               // 1: ml.PingResponse
	(*PredictRequest)(nil),             // 2: ml.PredictRequest
	(*PredictResponse)(nil),            // 3: ml.PredictResponse
	(*HorizonPrediction)(nil),          // 4: ml.HorizonPrediction
	(*TrainModelRequest)(nil),          // 5: ml.TrainModelRequest
	(*TrainModelResponse)(nil),         // 6: ml.TrainModelResponse
	(*ModelInfoRequest)(nil),           // 7: ml.ModelInfoRequest
	(*ModelInfoResponse)(nil),          // 8: ml.ModelInfoResponse
	(*ModelInfo)(nil),                  // 9: ml.ModelInfo
	(*ModelMetrics)(nil),               // 10: ml.ModelMetrics
	(*TriggerTrainingRequest)(nil),     // 11: ml.TriggerTrainingRequest
	(*TriggerTrainingResponse)(nil),    // 12: ml.TriggerTrainingResponse
	(*RunWeeklyPortfolioRequest)(nil),  // 13: ml.RunWeeklyPortfolioRequest
	(*RunWeeklyPortfolioResponse)(nil), // 14: ml.RunWeeklyPortfolioResponse
	(*TriggerBulkRetrainRequest)(nil),  // 15: ml.TriggerBulkRetrainRequest
	(*BulkRetrainUpdate)(nil),          // 16: ml.BulkRetrainUpdate
	nil,                                // 17: ml.PredictRequest.FeaturesEntry
	nil,                                // 18: ml.ModelInfo.HyperparametersEntry
}
var file_proto_ml_ml_service_proto_depIdxs = []int32{
	17, // 0: ml.PredictRequest.features:type_name -> ml.PredictRequest.FeaturesEntry
	4,  // 1: ml.PredictResponse.predictions:type_name -> ml.HorizonPrediction
	10, // 2: ml.TrainModelResponse.metrics:type_name -> ml.ModelMetrics
	9,  // 3: ml.ModelInfoResponse.models:type_name -> ml.ModelInfo
	18, // 4: ml.ModelInfo.hyperparameters:type_name -> ml.ModelInfo.HyperparametersEntry
	10, // 5: ml.ModelInfo.metrics:type_name -> ml.ModelMetrics
	2,  // 6: ml.MLPredictionService.Predict:input_type -> ml.PredictRequest
	5,  // 7: ml.MLPredictionService.TrainModel:input_type -> ml.TrainModelRequest
	7,  // 8: ml.MLPredictionService.GetModelInfo:input_type -> ml.ModelInfoRequest
	0,  // 9: ml.MLPredictionService.Ping:input_type -> ml.PingRequest
	11, // 10: ml.MLPredictionService.TriggerTraining:input_type -> ml.TriggerTrainingRequest
	13, // 11: ml.MLPredictionService.RunWeeklyPortfolio:input_type -> ml.RunWeeklyPortfolioRequest
	15, // 12: ml.MLPredictionService.TriggerBulkRetrain:input_type -> ml.TriggerBulkRetrainRequest
	3,  // 13: ml.MLPredictionService.Predict:output_type -> ml.PredictResponse
	6,  // 14: ml.MLPredictionService.TrainModel:output_type -> ml.TrainModelResponse
	8,  // 15: ml.MLPredictionService.GetModelInfo:output_type -> ml.ModelInfoResponse
	1,  // 16: ml.MLPredictionService.Ping:output_type -> ml.PingResponse
	12, // 17: ml.MLPredictionService.TriggerTraining:output_type -> ml.TriggerTrainingResponse
	14, // 18: ml.MLPredictionService.RunWeeklyPortfolio:output_type -> ml.RunWeeklyPortfolioResponse
	16, // 19: ml.MLPredictionService.TriggerBulkRetrain:output_type -> ml.BulkRetrainUpdate
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_ml_ml_service_proto_init() }
func file_proto_ml_ml_service_proto_init() {
	if File_proto_ml_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ml_ml_service_proto_rawDesc), len(file_proto_ml_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ml_ml_service_proto_goTypes,
		DependencyIndexes: file_proto_ml_ml_service_proto_depIdxs,
		MessageInfos:      file_proto_ml_ml_service_proto_msgTypes,
	}.Build()
	File_proto_ml_ml_service_proto = out.File
	file_proto_ml_ml_service_proto_goTypes = nil
	file_proto_ml_ml_service_proto_depIdxs = nil
}
